name: Daily Build

on:
  schedule:
    # Run at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # Linux builds
          - os: linux
            arch: amd64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-latest

          # macOS builds
          - os: darwin
            arch: amd64
            runner: macos-latest
          - os: darwin
            arch: arm64
            runner: macos-latest

          # Windows builds
          - os: windows
            arch: amd64
            runner: windows-latest
          - os: windows
            arch: arm64
            runner: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
          cache-dependency-path: pfs-server/go.sum

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            # For Windows, use PowerShell installer
            powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
            echo "$HOME/AppData/Roaming/Python/Scripts" >> $GITHUB_PATH
          else
            # For Unix
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      - name: Get version info
        id: version
        shell: bash
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build pfs-server
        working-directory: pfs-server
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.date }}-${{ steps.version.outputs.short_sha }}" -o ../build/pfs-server-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }} ./cmd/server

      - name: Build pfs-shell (portable)
        if: matrix.arch == 'amd64' || (matrix.os == 'darwin' && matrix.arch == 'arm64')
        shell: bash
        run: |
          cd pfs-shell

          # Find uv command
          if command -v uv &> /dev/null; then
            UV_CMD="uv"
          elif [ -f "$HOME/.cargo/bin/uv" ]; then
            UV_CMD="$HOME/.cargo/bin/uv"
          else
            echo "Error: uv not found"
            exit 1
          fi

          echo "Using uv: $UV_CMD"
          $UV_CMD --version

          # Sync dependencies
          $UV_CMD sync

          # Build portable distribution
          python3 build.py

          # Create archive name
          ARCHIVE_NAME="pfs-shell-${{ matrix.os }}-${{ matrix.arch }}"

          # Package the portable distribution
          if [ "${{ matrix.os }}" = "windows" ]; then
            # For Windows, create zip
            cd dist
            powershell Compress-Archive -Path pfs-portable -DestinationPath "../../build/${ARCHIVE_NAME}.zip"
          else
            # For Unix, create tar.gz
            cd dist
            tar -czf "../../build/${ARCHIVE_NAME}.tar.gz" pfs-portable/
          fi

      - name: Create archive (Unix)
        if: matrix.os != 'windows'
        working-directory: build
        run: |
          tar -czf pfs-${{ matrix.os }}-${{ matrix.arch }}-${{ steps.version.outputs.date }}.tar.gz pfs-server-${{ matrix.os }}-${{ matrix.arch }}*

      - name: Create archive (Windows)
        if: matrix.os == 'windows'
        working-directory: build
        shell: pwsh
        run: |
          $files = Get-ChildItem -Filter "pfs-*-${{ matrix.os }}-${{ matrix.arch }}*"
          Compress-Archive -Path $files -DestinationPath "pfs-${{ matrix.os }}-${{ matrix.arch }}-${{ steps.version.outputs.date }}.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pfs-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            build/pfs-${{ matrix.os }}-${{ matrix.arch }}-*.tar.gz
            build/pfs-${{ matrix.os }}-${{ matrix.arch }}-*.zip
            build/pfs-shell-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            build/pfs-shell-${{ matrix.os }}-${{ matrix.arch }}.zip
          retention-days: 90

  create-release:
    name: Create Daily Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version info
        id: version
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "tag=nightly" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Display structure of downloaded files
        run: ls -R release-artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find release-artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec cp {} release/ \;

      - name: Delete existing nightly release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete nightly --yes --cleanup-tag

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build (${{ steps.version.outputs.date }})
          body: |
            ## Daily Build - ${{ steps.version.outputs.date }}

            Automated daily build from commit ${{ github.sha }}

            ### 📦 What's Included

            This release contains:
            - **pfs-server**: Go binary (server)
            - **pfs-shell**: Python portable CLI client (requires Python 3.10+, includes all dependencies)

            ### Downloads

            #### Server Binaries

            - **Linux AMD64**: `pfs-linux-amd64-${{ steps.version.outputs.date }}.tar.gz`
            - **Linux ARM64**: `pfs-linux-arm64-${{ steps.version.outputs.date }}.tar.gz`
            - **macOS AMD64**: `pfs-darwin-amd64-${{ steps.version.outputs.date }}.tar.gz`
            - **macOS ARM64 (Apple Silicon)**: `pfs-darwin-arm64-${{ steps.version.outputs.date }}.tar.gz`
            - **Windows AMD64**: `pfs-windows-amd64-${{ steps.version.outputs.date }}.zip`
            - **Windows ARM64**: `pfs-windows-arm64-${{ steps.version.outputs.date }}.zip`

            #### CLI Client (Portable, Python 3.10+ required)

            - **Linux AMD64**: `pfs-shell-linux-amd64.tar.gz`
            - **macOS AMD64**: `pfs-shell-darwin-amd64.tar.gz`
            - **macOS ARM64**: `pfs-shell-darwin-arm64.tar.gz`
            - **Windows AMD64**: `pfs-shell-windows-amd64.zip`

            ### Installation

            #### Quick Install (All-in-One)

            ```bash
            curl -fsSL https://raw.githubusercontent.com/c4pt0r/pfs/master/install.sh | sh
            ```

            This will install both server and client to `~/.local/bin/`.

            #### Manual Installation

            **Server (Linux/macOS):**
            ```bash
            # Extract
            tar -xzf pfs-<os>-<arch>-${{ steps.version.outputs.date }}.tar.gz

            # Make executable
            chmod +x pfs-server-<os>-<arch>

            # Move to bin directory
            mv pfs-server-<os>-<arch> ~/.local/bin/pfs-server

            # Run server
            pfs-server
            ```

            **Client (Linux/macOS):**
            ```bash
            # Extract
            tar -xzf pfs-shell-<os>-<arch>.tar.gz

            # Run directly
            ./pfs-portable/pfs --help

            # Or install to system
            cd pfs-portable && ./install.sh
            ```

            **Windows:**
            ```powershell
            # Extract server
            Expand-Archive pfs-windows-amd64-${{ steps.version.outputs.date }}.zip

            # Extract client
            Expand-Archive pfs-shell-windows-amd64.zip

            # Run server
            .\pfs-server-windows-amd64.exe

            # Run client
            .\pfs-portable\pfs.bat --help
            ```

            ### Quick Start

            ```bash
            # Start the server
            pfs-server

            # In another terminal, use CLI
            pfs shell
            pfs ls /
            pfs tree /
            ```
          files: release/*
          draft: false
          prerelease: true
